### ISSUE TITLE
The header logo on mobile device looks very small...

### ISSUE THREAD

**Issue by marqub** [zerostaticthemes/hugo-serif-theme#35]
Hi,

I'm using a svg image as my logo. It's displayed correctly on desktop devices (once I played with `.Site.Params.logo.desktop_height`) but is really small on any mobile device. I also tried to modify the header.html to force a size but it has no effect at all... What am I missing?

```
<div class='header'>
  <div class="container">
    <div class="logo">
      <a href="{{ .Site.BaseURL }}"><img height={{ .Site.Params.logo.desktop_height }} alt="{{ .Site.Params.logo.alt }}" src="{{ .Site.Params.logo.desktop | relURL }}" /></a>
    </div>
    <div class="logo-mobile">
      <a href="{{ .Site.BaseURL }}"><img height="2000px" alt="{{ .Site.Params.logo.alt }}" src="{{ .Site.Params.logo.mobile | relURL }}" /></a>
    </div>
    {{ partial "main-menu.html" . }}
    {{ partial "hamburger.html" . }}
  </div>
</div>
```
Thanks

**Comment by JugglerX** [comment]
@marqub I made an update that should fix this. Setting a height in the HTML should now work as expected. It was being overridden by the css
