### ISSUE TITLE
Pull color configuration to theme config / settings

### ISSUE THREAD

**Issue by splatch** [zerostaticthemes/hugo-serif-theme#37]
I come across serif theme and I really like your work. Given my limited knowledge of scss I was stuck at very basic problem - adjusting of theme colors. I've tried to create `_bootstrap-variables` as well as `bootstrap-variables` files with mixed results.

At the same time I found other themes making syle colors configurable:
https://github.com/vaga/hugo-theme-m10c/blob/master/assets/css/main.scss#L1L5

Would you consider moving color config to theme settings? If so I can try to come with an PR.

**Comment by JugglerX** [comment]
@splatch to change the color variables you can just edit the `scss/style.scss` Line 2.

If you want to override bootstrap variables then edit the existing `scss/_bootstrap-variables.scss`

About your suggestion to use color variables in the `config.toml` - yes, I am familiar with this approach. If you want to do a PR which adds this feature go ahead.
