### ISSUE TITLE
change logo to png fails to load file

### ISSUE THREAD

**Issue by OctoberMedia** [zerostaticthemes/hugo-serif-theme#39]
Very clean theme. Thank you for creating it.
I have a minor problem and am not sure if it is me or a theme configuration.
Using brand new homebrew version of Hugo

hugo v0.85.0+extended darwin/amd64 

Upload my log png to static/images/ logos
changed config file to use new png file
However the theme wont display this - Only seems to be able to display svg files

Many thanks in advance for any pointers

**Comment by JugglerX** [comment]
@OctoberMedia png files will work. Double check your paths, clear cache and fully restart the server.
