### ISSUE TITLE
Embedding services pages into main page

### ISSUE THREAD

**Issue by ozancaglayan** [zerostaticthemes/hugo-serif-theme#41]
Hi,

Is there a way to actually include all services in the main `index.html` file with proper styling of their titles and content? In my case, the accompanying text for each service is rather small and their individual page appears somewhat empty when clicked. I tried dumping them in Markdown into `index.md` but that is styled in a way to flow on the left side of the main page visual.

Thanks!

**Comment by JugglerX** [comment]
You can modify the homepage template to display all the services. https://github.com/zerostaticthemes/hugo-serif-theme/blob/1c8aee0c6866a35460cf9d09196ce1511da531ed/layouts/index.html#L28 

Edit `{{ range first 6 (sort $services ".Params.weight") }}` to `{{ range (sort $services ".Params.weight") }}`


I'm not sure what you mean by proper styling and titles and content. You can edit the CSS file to modify the styles of the services on the homepage.
