### ISSUE TITLE
Safari iOs 15.0.2 - mobile version - menu doesn't show / work

### ISSUE THREAD

**Issue by mbrissaud** [zerostaticthemes/hugo-serif-theme#44]
Hi,
Great theme.
Works perfectly with firefox for iOs.
With safari, the menu (up-right) doesn't show / work.
Do you think there is a work around?
Thanks,
Mathieu

**Comment by JugglerX** [comment]
I just tested it on iOs 15.4 and it worked for me. 

I did notice once the menu is opened, its possible to scroll and the menu close button X is no longer visible. It looks like the new Safari has placed the url bar on the bottom which is causing this problem.

**Comment by mbrissaud** [comment]
Hi,
On iOS 15.0.2 the only way to make 'hamburger menu' work on Safari is to enable JavaScript in the advanced settings.
By default, this option is disabled on Safari while it is enabled on Firefox for iOS...
As soon as I upgrade iOS to 15.4 I'll retry and let you know.
Thanks,
Mathieu

**Comment by JugglerX** [comment]
I don't believe Javascript is disabled by default on Safari. The entire internet would not work.

Sounds like you had javascript disabled.
