### ISSUE TITLE
Hamburger has some strange opacity bugs

### ISSUE THREAD

**Issue by Mk-arc** [zerostaticthemes/hugo-serif-theme#45]
Hi,

visiting the theme in a small window and using the "hamburger" results in some strange artifacts.

![image](https://user-images.githubusercontent.com/15717249/158035424-d38abb2c-b119-4c7b-88c5-c26e8ea7c5f5.png)

**Comment by Mk-arc** [comment]
changing the opacity to 1.0 in _main-menu-mobile.scss fixes the ugly artifacts. Of course then there is no more opacity. But its fine for me. Still looks nice. 

So I will close this issue, since its not relevant to me anymore.

**Comment by JugglerX** [comment]
Ive noticed this recently as well. Its bloodie baffling where it came from. If anyone knows a fix where we can keep the opacity id appreciate a PR.

**Comment by JugglerX** [comment]
Can no longer reproduce, seems to be fixed
