### ISSUE TITLE
Deploy Issue

### ISSUE THREAD

**Issue by OnPointSM** [zerostaticthemes/hugo-serif-theme#51]
My Render deploy does not work. I get multiple repetitions of the same problem. Anybody struggling with this one?

`Apr 25 12:04:18 AM   WARN 2022/04/24 22:04:18 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`

**Comment by JugglerX** [comment]
I was able to deploy on render just fine. Did you ever fix the issue?
