### ISSUE TITLE
Change colours in config.toml

### ISSUE THREAD

**Issue by anelda** [zerostaticthemes/hugo-serif-theme#52]
Good day, 

I would like to edit the colour scheme of the theme and followed the method suggested in the README (adding info to the config.toml file).

It isn't taking effect however. When I look at the scss it still has the original colours and that file can't be changed.

- Hugo version: hugo v0.89.0-ADE966B8+extended linux/amd64 BuildDate=2021-11-02T10:00:18Z VendorInfo=gohugoio
- Repo: https://gitlab.com/rsse-africa/rsse-africa-website
- Website: https://rsse.africa/

I looked for tips on the internet, but couldn't find anything that worked to solve my problem. 

I'd greatly appreciate any help.

Kind regards,
Anelda

**Comment by jdbarillas** [comment]
You might have the old version of the theme, where the way to change it was different.


From the old README:

> ### Colors
>
> You can edit the themes primary, secondary and neutral colors in `scss/style.scss`. To override the bootstrap colors > simply edit `scss/_bootstrap-variables.scss`
>
>```scss
>// scss/style.scss
>
>// Colors
>$primary: #f24088;
>$secondary: #f88379;
>$black: #2f2f41;
>$white: #ffffff;
>$white-offset: #f6f7ff;
>$steel: #5C5A5A;
>```
