### ISSUE TITLE
favicon and title text beside favicon

### ISSUE THREAD

**Issue by alanyang0924** [zerostaticthemes/hugo-serif-theme#54]
Hi,
I couldn't figure out how to change the favicon and the text that shows up on the website's tab in a web browser(e.g. a Google chrome tab). It shows "Hugo Serif Theme" currently with a pink square and white "S" favicon. Please help and thank you!

**Comment by JugglerX** [comment]
the frontmatter `title` or `meta_title` property is used for the browser <title>

To update the title for the homepage edit `content/_index.md` and change the `meta_title` frontmatter property, or delete it and change the `title` property

The favicon is an image inside the `static` folder, just overwrite it with your own image.
