### ISSUE TITLE
Upgrade to Bootstrap 5.2.1

### ISSUE THREAD

**Issue by mostlyvirtual** [zerostaticthemes/hugo-serif-theme#68]
I was thinking it would be nice to upgrade the CSS to Bootstrap 5.x and it looks like 5.2.1 is the latest available.
After checking, it seems like it would be almost a 1-for-1 swap, with very small tweaks, since you're using very little of the library by default.

Once Bootstrap 5 is in place, we could potentially take advantage of some of the new features it has to offer.

Is this something you would be interested in doing, please let me know and I'll create a PR. Thanks.

**Comment by JugglerX** [comment]
@mostlyvirtual yes I would like to upgrade it to the latest version of Bootstrap. A PR would be great.

**Comment by JugglerX** [comment]
Fixed in latest release v1.3 - Upgraded to Bootstrap 5.3
