### ISSUE TITLE
Sitemap issue with Google

### ISSUE THREAD

**Issue by protofrancesco** [zerostaticthemes/hugo-serif-theme#71]
Hello, I've used the theme (it's great, btw), develop the website and successfully deployed with Netlify. Though, I'm having some issues with Google Search Console: basically, it says that the sitemap I've generated is valid but contains some errors on the urls. 
What you think could be the problem?

**Comment by JugglerX** [comment]
No idea. Could you provide the Google Search Console report and the link to your repo and sitemap file?

**Comment by protofrancesco** [comment]
Yeah sure. Thanks for your reply! 
[Repo](https://github.com/protofrancesco/shed626-nuovo.git)

Google S C: "La Sitemap può essere letta, ma presenta errori
URL non valido
20 istanze
L'URL non è valido. Correggilo e reinvia" 
I cannot attach the sitemap file but it is in the repo. 
I'm not a professional dev whatsoever so there might be lots of mistakes.
