### ISSUE TITLE
Different images for dark mode?

### ISSUE THREAD

**Issue by tamis-laan** [zerostaticthemes/hugo-serif-theme#80]
I would like to use different images based on light or dark mode as they don't always work with such extremely different color schemes. Or I would like to set the website permanently to dark or light mode. Is this possible?

**Comment by JugglerX** [comment]
Hi Yes you would first need to implement dark mode. Its possible but no plans to add it myself. You will need to make a PR or rely on the community.

Alternatively I have several premium themes that ship with Dark mode available at www.zerostatic.io
