### ISSUE TITLE
Logo moves horizontally between pages

### ISSUE THREAD

**Issue by jonas-karlsson** [zerostaticthemes/hugo-serif-theme#82]
If you switch quickly between pages, for examples

https://hugo-serif.netlify.app/services/ and
https://hugo-serif.netlify.app/team/

You will see the top left logo moving horizontally (it moves right it `team` compared to `services`).

I'm not proficient enough in CSS to fix it with a PR myself, sorry.

**My system**
Chrome
Version 122.0.6261.129 (Official Build) (x86_64)

MacOs Sonoma 14.4 (23E214)

**Comment by JugglerX** [comment]
I dont see it.

Probably because one page has a scroll bar while the other doesnt. So its just how the web works. 

if you can identify an actual css bug, feel free to PR.

**Comment by jonas-karlsson** [comment]
Ah, that's what causing the shift. I found this [Preventing the Layout Shift Caused by Scrollbars](https://dev.to/rashidshamloo/preventing-the-layout-shift-caused-by-scrollbars-2flp) and will test it. If it works I'll send it back as a PR.
