### ISSUE TITLE
Replace .Site.IsServer with hugo.IsServer

### ISSUE THREAD

**Issue by argus-core** [zerostaticthemes/hugo-serif-theme#87]
Deploying with a newer version of Hugo (e.g. v0.132.2+extended currently used in the GitLab Hugo template) fails with the following error:

`ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.133.0. Use hugo.IsServer instead.`

The following files require updating:
layouts/404.html
layouts/partials/google-analytics.html
layouts/partials/google-tag-manager.html
layouts/partials/google-tag-manager-noscript.html

**Comment by argus-core** [comment]
Looks like @jsmolic already created one, I didn't think to check before opening the issue: https://github.com/zerostaticthemes/hugo-serif-theme/pull/86

**Comment by vkosuri** [comment]
Any plans to merge #86?

**Comment by JugglerX** [comment]
Merged, thank you all.
